baseURL: https://kraegpoeth.github.io/resume
languageCode: en-us
title: krgpth
theme: hugo-coder

params:
  author: Kasper Krægpøth
  info: Senior frontend developer
  description: krgpth portfolio
  keywords: "frontend,developer,personal,resume"
  avatarurl: /img/avatar.jpeg
  favicon_32: /img/favicon/32.png
  favicon_16: /img/favicon/64.png
  since: 2023
  enableTwemoji: true
  colorScheme: auto
  hidecolorschemetoggle: false
  # customCSS:
  #   - css/custom.css
  # customSCSS:
  #   - scss/custom.scss
  # customJS:
  #   - js/custom.js
  social:
    - name: Website
      icon: fa fa-globe fa-2x
      weight: 1
      url: "https://krgpth.com/"
    - name: Github
      icon: fa fa-github fa-2x
      weight: 1
      url: "https://github.com/kraegpoeth/"
    - name: Gitlab
      icon: fa fa-gitlab fa-2x
      weight: 2
      url: "https://gitlab.com/kraegpoeth1/"
    - name: Linkedin
      icon: fa fa-linkedin fa-2x
      weight: 3
      url: "https://linkedin.com/in/kraegpoeth/"
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
menu:
  main:
    - name: About
      weight: 2
      url: about/
    - name: Resumé
      weight: 1
      url: cv/
    - name: Skills
      weight: 1
      url: skills/
    - name: Contact
      weight: 2
      url: contact/
